name: Basic Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '11', '17' ]
    name: Basic Build (Java ${{ matrix.Java }})

    steps:
    - uses: actions/checkout@v1
    - name: Setup java
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: ${{ matrix.java }}
    - name: Test
      run: ./gradlew ciBasicBuild
